/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as CyberLabRouteImport } from './routes/cyber-lab'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as ApiSessionsRouteImport } from './routes/api.sessions'
import { Route as ApiSessionMessagesRouteImport } from './routes/api.session-messages'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiSessionsCompleteRouteImport } from './routes/api.sessions.complete'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberLabRoute = CyberLabRouteImport.update({
  id: '/cyber-lab',
  path: '/cyber-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionMessagesRoute = ApiSessionMessagesRouteImport.update({
  id: '/api/session-messages',
  path: '/api/session-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsCompleteRoute = ApiSessionsCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => ApiSessionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/cyber-lab': typeof CyberLabRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tools': typeof ToolsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/session-messages': typeof ApiSessionMessagesRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/api/sessions/complete': typeof ApiSessionsCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/cyber-lab': typeof CyberLabRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tools': typeof ToolsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/session-messages': typeof ApiSessionMessagesRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/api/sessions/complete': typeof ApiSessionsCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/cyber-lab': typeof CyberLabRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tools': typeof ToolsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/session-messages': typeof ApiSessionMessagesRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/api/sessions/complete': typeof ApiSessionsCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chat'
    | '/cyber-lab'
    | '/learn'
    | '/login'
    | '/signup'
    | '/tools'
    | '/api/chat'
    | '/api/session-messages'
    | '/api/sessions'
    | '/api/upload'
    | '/api/sessions/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chat'
    | '/cyber-lab'
    | '/learn'
    | '/login'
    | '/signup'
    | '/tools'
    | '/api/chat'
    | '/api/session-messages'
    | '/api/sessions'
    | '/api/upload'
    | '/api/sessions/complete'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chat'
    | '/cyber-lab'
    | '/learn'
    | '/login'
    | '/signup'
    | '/tools'
    | '/api/chat'
    | '/api/session-messages'
    | '/api/sessions'
    | '/api/upload'
    | '/api/sessions/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChatRoute: typeof ChatRoute
  CyberLabRoute: typeof CyberLabRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ToolsRoute: typeof ToolsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSessionMessagesRoute: typeof ApiSessionMessagesRoute
  ApiSessionsRoute: typeof ApiSessionsRouteWithChildren
  ApiUploadRoute: typeof ApiUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyber-lab': {
      id: '/cyber-lab'
      path: '/cyber-lab'
      fullPath: '/cyber-lab'
      preLoaderRoute: typeof CyberLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-messages': {
      id: '/api/session-messages'
      path: '/api/session-messages'
      fullPath: '/api/session-messages'
      preLoaderRoute: typeof ApiSessionMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/complete': {
      id: '/api/sessions/complete'
      path: '/complete'
      fullPath: '/api/sessions/complete'
      preLoaderRoute: typeof ApiSessionsCompleteRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
  }
}

interface ApiSessionsRouteChildren {
  ApiSessionsCompleteRoute: typeof ApiSessionsCompleteRoute
}

const ApiSessionsRouteChildren: ApiSessionsRouteChildren = {
  ApiSessionsCompleteRoute: ApiSessionsCompleteRoute,
}

const ApiSessionsRouteWithChildren = ApiSessionsRoute._addFileChildren(
  ApiSessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChatRoute: ChatRoute,
  CyberLabRoute: CyberLabRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ToolsRoute: ToolsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSessionMessagesRoute: ApiSessionMessagesRoute,
  ApiSessionsRoute: ApiSessionsRouteWithChildren,
  ApiUploadRoute: ApiUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
