/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as CyberLabRouteImport } from './routes/cyber-lab'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSessionsRouteImport } from './routes/api.sessions'
import { Route as ApiSessionMessagesRouteImport } from './routes/api.session-messages'
import { Route as ApiChatRouteImport } from './routes/api.chat'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberLabRoute = CyberLabRouteImport.update({
  id: '/cyber-lab',
  path: '/cyber-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionMessagesRoute = ApiSessionMessagesRouteImport.update({
  id: '/api/session-messages',
  path: '/api/session-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/cyber-lab': typeof CyberLabRoute
  '/learn': typeof LearnRoute
  '/tools': typeof ToolsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/session-messages': typeof ApiSessionMessagesRoute
  '/api/sessions': typeof ApiSessionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/cyber-lab': typeof CyberLabRoute
  '/learn': typeof LearnRoute
  '/tools': typeof ToolsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/session-messages': typeof ApiSessionMessagesRoute
  '/api/sessions': typeof ApiSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/cyber-lab': typeof CyberLabRoute
  '/learn': typeof LearnRoute
  '/tools': typeof ToolsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/session-messages': typeof ApiSessionMessagesRoute
  '/api/sessions': typeof ApiSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chat'
    | '/cyber-lab'
    | '/learn'
    | '/tools'
    | '/api/chat'
    | '/api/session-messages'
    | '/api/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chat'
    | '/cyber-lab'
    | '/learn'
    | '/tools'
    | '/api/chat'
    | '/api/session-messages'
    | '/api/sessions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chat'
    | '/cyber-lab'
    | '/learn'
    | '/tools'
    | '/api/chat'
    | '/api/session-messages'
    | '/api/sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChatRoute: typeof ChatRoute
  CyberLabRoute: typeof CyberLabRoute
  LearnRoute: typeof LearnRoute
  ToolsRoute: typeof ToolsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSessionMessagesRoute: typeof ApiSessionMessagesRoute
  ApiSessionsRoute: typeof ApiSessionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyber-lab': {
      id: '/cyber-lab'
      path: '/cyber-lab'
      fullPath: '/cyber-lab'
      preLoaderRoute: typeof CyberLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-messages': {
      id: '/api/session-messages'
      path: '/api/session-messages'
      fullPath: '/api/session-messages'
      preLoaderRoute: typeof ApiSessionMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChatRoute: ChatRoute,
  CyberLabRoute: CyberLabRoute,
  LearnRoute: LearnRoute,
  ToolsRoute: ToolsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSessionMessagesRoute: ApiSessionMessagesRoute,
  ApiSessionsRoute: ApiSessionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
